[package]
name = "gettersetter"
version = "0.1.0"
authors = ["karan.patel <karan.patel@verse.in>"]
edition = "2018"

[lib]
proc-macro=true

[dependencies]
quote="^0.3.12"
syn="^0.11.4"

[[example]]
name="example"
path="src/example.rs"